name: uli-mc
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.0.1=pyhd8ed1ab_0
  - sympy=1.7.1
  - matplotlib=3.3.4
  - numpy=1.20.1
  - scipy=1.6.0
  - control=0.8.4
  - pydot=1.4.1
  - autopep8=1.5.5
  - pytest=5.0.1
  - jupyterlab=3.0.7
  - ffmpeg=4.3.1
  - openh264=2.1.1
  - pandas=1.2.2
  - pip:
    - casadi==3.5.5
    - picos==2.2.0
    - pyhull==2015.2.1
    - nbdime==2.1.0